version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: hesk_bot_cache
    restart: always
    volumes:
      - /tmp/redis_d–∞ta:/root/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DATA_DIR=/root/redis
    networks:
      - my_net
  bot:
    build: .
    container_name: hesk_bot
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    networks:
      - my_net
      - my_net_ext

networks:
  my_net:
    driver: bridge
  my_net_ext:
    external: true