version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: hesk_bot_cache
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - /tmp/redis_d–∞ta:/root/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DATA_DIR=/root/redis
    network_mode: host

  bot:
    build: .
    container_name: hesk_bot
    restart: always
    env_file:
      - .env
    network_mode: host